import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sidebar/navBar";
import { Chewy as ChewyFont } from "next/font/google";

const chewy = ChewyFont({ subsets: ["latin"], weight: "400" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chewy.className}`}>
        <Navbar />
        <div className="flex flex-col items-center justify-center min-h-screen bg-gray-200 bg-[url('/images/pokemon2.png')] bg-cover bg-center h-64 w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
